personalInfo:
  # Load from environment secret to prevent personal info leaking
  # If you are using replit free plan, set this true
  # Then add your info to the secrets section
  loadFromEnv: false

  # if loadFromEnv is true, anything in personalInfo beside typeId is ignored
  firstName: 'Ramya'
  lastName: 'Jami'
  # Date of birth (MM/DD/YYYY)
  dob: '06/23/1991'
  # Use real email to get appointment infomation
  email: 'ramyasunkara3@gmail.com'
  # Not really needed but good to have a real one
  lastFourSSN: '2485'
  # If you want to recieve notificaion through phone, if not keep blank
  # WARNING: Use number only (Ex: 111111111)
  phoneNumber: '4084429995'

  # Serivce you needed at DPS. Check the full list on https://github.com/phamleduy04/texas-dps-scheduler/wiki/TypeId-list
  # If you need to apply for Texas DL you don't need to change it
  typeId: 71

location:
  # Zipcode of your location
  zipCode: '75189'
  # Choose your DPS location by yourself when running the application if set to true
  pickDPSLocation: false
  # Get appointment from all DPS location by distance from the zipcode, will auto skip this when pickDPSLocation is true
  miles: 25
  # Put empty [''] for any day
  # DPS is closed on weekends, so you can't book on Saturday and Sunday
  preferredDays: ['']
  # Put true/false without quotes if you want to book only same day appointment
  sameDay: false
  # Put how many day from today you want to book from start to end (7 is a good number)
  daysAround:
    start: 0
    end: 7
  # Put what time you want to book
  timesAround:
    # Number in 24h format, start = 6 and end = 18 means get appointment between 6 AM - 6 PM
    start: 6
    end: 18

appSettings:
  # Put true/false without quotes if you want to cancel the appointment automatically if found existing appointment
  cancelIfExist: true
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: false
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 20000 
  # How many times to retry if the request to DPS server failled
  maxRetry: 3

# If you dont know what to change here, dont change it :)
webhook:
  # If your using Bluebubbles webhook/api put this to true otherwise, keep it false
  enable: false
  url: ''
  password: ''
  # phone number with country code (EX: +11111111111)
  phoneNumber: ''
  # private-api or apple-script
  sendMethod: 'apple-script'
  # iMessage or SMS
  phoneNumberType: 'SMS'